name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.7

      - name: Install Cloudflare SSL
        run: go install github.com/cloudflare/cfssl/cmd/cfssl@v1.4.1

      - name: Install Cloudflare SSL JSON
        run: go install github.com/cloudflare/cfssl/cmd/cfssljson@v1.4.1

      - name: Make certs
        run: make init && make gencert

      - name: Build
        run: go build -v ./...

      - name: Vet
        run: go vet ./...

      - name: Shadow
        run: go install golang.org/x/tools/go/analysis/passes/shadow/cmd/shadow@latest && shadow ./...

      - name: Test
        run: go test -v ./... -race -covermode=atomic -coverprofile=coverage.out

      - name: Go report card
        uses: creekorful/goreportcard-action@v1.0

      - name: Remove certs
        run: make deinit